FROM python:3.12-slim AS builder


WORKDIR /app


RUN pip install --no-cache-dir uv


COPY pyproject.toml uv.lock ./


RUN uv venv /opt/venv && \
    . /opt/venv/bin/activate && \
    uv sync --no-dev


FROM python:3.12-slim


COPY --from=builder /opt/venv /opt/venv


ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1


WORKDIR /app
COPY . .


EXPOSE 8000


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]